### ISSUE TITLE
心率数据是从早上9点开始返回的吗?

### ISSUE THREAD

**Issue by xslgithub** [xuezou/Lib3Framework-iOS#1]
除了- (void)startSpecialData:(SD_TYPE)sdType withDate:(NSDate *)date 这个方法 还有其它方法能返回 心率的数据吗?

**Comment by xuezou** [comment]
同步数据都是使用这个方法

**Comment by xuezou** [comment]
数据没有所谓的几点开始返回的，设备采集了就有，没采集就无。同步逻辑管不了那么多，只是根据设备的情况去获取数据

**Comment by xslgithub** [comment]
这个数据是分时段返回的 
[self.bleSolstice startSpecialData:SD_TYPE_HEART_RATE withDate:[NSDate date]];
![image](https://user-images.githubusercontent.com/15224779/59737186-37767700-928f-11e9-9483-29014a899626.png)
有没有直接返回一天的方法,包括艾维示例程序内的那种一天的心率返回 包括最大值 最小值 平均值

**Comment by xuezou** [comment]
不同的设备方法不太一样，SDK设计的是兼容所有数据类型的。像这个心率的都是以小时计，但是开启同步之后可以获得所有未同步的数据
