### ISSUE TITLE
how to get calorie and distance data in minute 

### ISSUE THREAD

**Issue by itoni2014** [xuezou/Lib3Framework-iOS#2]
I already got step data in minute. 
Now I want to get calorie and distance data in minute also,  I tried many times and I failed.

Could you tell me is there a method to get it and give me some idea ?
I will  appreciate for it.
Thank you.

**Comment by xuezou** [comment]
Did you had got step data in minute by this method "- (void)updateNormalHealthData:(ZRHealthData *)zrhData"?  If true, you can also get calorie and distance by it. The data model is different with device, you will find it by read in the ZRHealthData.h file. If not, tell me what device you used.

**Comment by itoni2014** [comment]
Thank you very much for your response.  Yes, I got it in that method. I will check the device.
